#include "vulkax/physics/dem_gpu.hpp"

#include <vulkan/vulkan.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <vector>

#ifndef VULKAX_GLSLANG_VALIDATOR_PATH
#define VULKAX_GLSLANG_VALIDATOR_PATH "glslangValidator"
#endif

namespace vulkax::physics::dem {
namespace {
struct alignas(16) ParticleGpu { float px{},py{},pz{},radius{};float vx{},vy{},vz{},mass{}; };
static_assert(sizeof(ParticleGpu)==32);
struct Push {std::uint32_t particleCount{},cellCount{},nx{},ny{};std::uint32_t nz{},capacity{};float dt{},cellSize{};float extentX{},extentY{},extentZ{},omega{};float gx{},gy{},gz{},pad{};float kn{},damping{},tangentialDamping{},friction{};float wallKn{},wallDamping{},wallTangentialDamping{},wallFriction{};};
static_assert(sizeof(Push)==96);
struct Buffer {VkBuffer buffer{VK_NULL_HANDLE};VkDeviceMemory memory{VK_NULL_HANDLE};void*mapped{};VkDeviceSize size{};};
void check(VkResult r,const char*w){if(r!=VK_SUCCESS)throw std::runtime_error(std::string(w)+" failed: "+std::to_string(r));}
std::uint32_t memoryType(VkPhysicalDevice p,std::uint32_t bits,VkMemoryPropertyFlags flags){VkPhysicalDeviceMemoryProperties m{};vkGetPhysicalDeviceMemoryProperties(p,&m);for(std::uint32_t i=0;i<m.memoryTypeCount;++i)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&flags)==flags)return i;throw std::runtime_error("GPU DEM host-visible coherent memory type unavailable");}
Buffer makeBuffer(VkPhysicalDevice p,VkDevice d,VkDeviceSize bytes){Buffer b;b.size=bytes;VkBufferCreateInfo ci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};ci.size=bytes;ci.usage=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT;ci.sharingMode=VK_SHARING_MODE_EXCLUSIVE;check(vkCreateBuffer(d,&ci,nullptr,&b.buffer),"vkCreateBuffer");VkMemoryRequirements req{};vkGetBufferMemoryRequirements(d,b.buffer,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType(p,req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);check(vkAllocateMemory(d,&ai,nullptr,&b.memory),"vkAllocateMemory");check(vkBindBufferMemory(d,b.buffer,b.memory,0),"vkBindBufferMemory");check(vkMapMemory(d,b.memory,0,bytes,0,&b.mapped),"vkMapMemory");return b;}
void destroy(VkDevice d,Buffer&b){if(b.mapped)vkUnmapMemory(d,b.memory);if(b.buffer)vkDestroyBuffer(d,b.buffer,nullptr);if(b.memory)vkFreeMemory(d,b.memory,nullptr);b={};}
std::vector<std::uint32_t> compile(const char*source,const char*tag){auto stamp=std::chrono::high_resolution_clock::now().time_since_epoch().count();auto base=std::filesystem::temp_directory_path()/(std::string("vulkax_dem_")+tag+"_"+std::to_string(stamp));auto glsl=base.string()+".comp",spv=base.string()+".spv";{std::ofstream out(glsl);if(!out)throw std::runtime_error("cannot create GPU DEM shader source");out<<source;}std::ostringstream cmd;cmd<<'"'<<VULKAX_GLSLANG_VALIDATOR_PATH<<"\" -V \""<<glsl<<"\" -o \""<<spv<<'"';int rc=std::system(cmd.str().c_str());std::filesystem::remove(glsl);if(rc!=0){std::filesystem::remove(spv);throw std::runtime_error("GPU DEM shader compilation failed");}std::ifstream in(spv,std::ios::binary|std::ios::ate);if(!in)throw std::runtime_error("cannot read GPU DEM SPIR-V");auto bytes=static_cast<std::size_t>(in.tellg());in.seekg(0);std::vector<std::uint32_t>w(bytes/4);in.read(reinterpret_cast<char*>(w.data()),static_cast<std::streamsize>(bytes));std::filesystem::remove(spv);return w;}
const char*binShader(){return R"glsl(#version 450
layout(local_size_x=128) in;
struct Particle { vec4 pr; vec4 vm; };
layout(std430,binding=0) readonly buffer InP { Particle particles[]; };
layout(std430,binding=2) buffer Counts { uint counts[]; };
layout(std430,binding=3) buffer Indices { uint indices[]; };
layout(push_constant) uniform Push {uint particleCount;uint cellCount;uint nx;uint ny;uint nz;uint capacity;float dt;float cellSize;float extentX;float extentY;float extentZ;float omega;float gx;float gy;float gz;float pad;float kn;float damping;float tangentialDamping;float friction;float wallKn;float wallDamping;float wallTangentialDamping;float wallFriction;} pc;
uvec3 cellOf(vec3 p){ivec3 c=ivec3(floor((p+vec3(pc.extentX,pc.extentY,pc.extentZ))/pc.cellSize));return uvec3(clamp(c,ivec3(0),ivec3(int(pc.nx)-1,int(pc.ny)-1,int(pc.nz)-1)));}
uint linearCell(uvec3 c){return (c.z*pc.ny+c.y)*pc.nx+c.x;}
void main(){uint i=gl_GlobalInvocationID.x;if(i>=pc.particleCount)return;uint c=linearCell(cellOf(particles[i].pr.xyz));uint slot=atomicAdd(counts[c],1u);if(slot<pc.capacity)indices[c*pc.capacity+slot]=i;}
)glsl";}
const char*stepShader(){return R"glsl(#version 450
layout(local_size_x=128) in;
struct Particle { vec4 pr; vec4 vm; };
layout(std430,binding=0) readonly buffer InP { Particle inputParticles[]; };
layout(std430,binding=1) writeonly buffer OutP { Particle outputParticles[]; };
layout(std430,binding=2) readonly buffer Counts { uint counts[]; };
layout(std430,binding=3) readonly buffer Indices { uint indices[]; };
layout(std430,binding=4) writeonly buffer Contacts { uint contactCounts[]; };
layout(push_constant) uniform Push {uint particleCount;uint cellCount;uint nx;uint ny;uint nz;uint capacity;float dt;float cellSize;float extentX;float extentY;float extentZ;float omega;float gx;float gy;float gz;float pad;float kn;float damping;float tangentialDamping;float friction;float wallKn;float wallDamping;float wallTangentialDamping;float wallFriction;} pc;
uvec3 cellOf(vec3 p){ivec3 c=ivec3(floor((p+vec3(pc.extentX,pc.extentY,pc.extentZ))/pc.cellSize));return uvec3(clamp(c,ivec3(0),ivec3(int(pc.nx)-1,int(pc.ny)-1,int(pc.nz)-1)));}
uint linearCell(uvec3 c){return (c.z*pc.ny+c.y)*pc.nx+c.x;}
vec3 pairForceOnI(Particle a,Particle b){vec3 delta=b.pr.xyz-a.pr.xyz;float dist=length(delta);float overlap=a.pr.w+b.pr.w-dist;if(overlap<=0.0||dist<=1e-8)return vec3(0);vec3 n=delta/dist;vec3 rel=b.vm.xyz-a.vm.xyz;float vn=dot(rel,n);float fn=max(0.0,pc.kn*overlap*sqrt(overlap)-pc.damping*vn);vec3 vt=rel-vn*n;float speed=length(vt);vec3 tang=vec3(0);if(speed>1e-8)tang=-vt/speed*min(pc.friction*fn,pc.tangentialDamping*speed);return -(n*fn+tang);}
vec3 wallForce(vec3 normal,vec3 relative,float overlap){float vn=dot(relative,normal);float fn=max(0.0,pc.wallKn*overlap*sqrt(overlap)-pc.wallDamping*vn);vec3 vt=relative-vn*normal;float speed=length(vt);vec3 tang=vec3(0);if(speed>1e-8)tang=-vt/speed*min(pc.wallFriction*fn,pc.wallTangentialDamping*speed);return normal*fn+tang;}
void main(){uint i=gl_GlobalInvocationID.x;if(i>=pc.particleCount)return;Particle a=inputParticles[i];vec3 force=vec3(pc.gx,pc.gy,pc.gz)*a.vm.w;uint contacts=0;uvec3 base=cellOf(a.pr.xyz);for(int dz=-1;dz<=1;++dz)for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx){ivec3 ci=ivec3(base)+ivec3(dx,dy,dz);if(any(lessThan(ci,ivec3(0)))||ci.x>=int(pc.nx)||ci.y>=int(pc.ny)||ci.z>=int(pc.nz))continue;uint cell=linearCell(uvec3(ci));uint count=min(counts[cell],pc.capacity);for(uint s=0;s<count;++s){uint j=indices[cell*pc.capacity+s];if(j==i)continue;Particle b=inputParticles[j];float overlap=a.pr.w+b.pr.w-length(b.pr.xyz-a.pr.xyz);if(overlap>0.0){force+=pairForceOnI(a,b);contacts++;}}}
float radial=length(a.pr.xy);if(radial+a.pr.w>pc.extentX&&radial>1e-8){vec3 n=vec3(-a.pr.x/radial,-a.pr.y/radial,0);vec3 wallVel=vec3(-pc.omega*a.pr.y,pc.omega*a.pr.x,0);force+=wallForce(n,a.vm.xyz-wallVel,radial+a.pr.w-pc.extentX);contacts++;}float top=a.pr.z+a.pr.w-pc.extentZ;if(top>0){force+=wallForce(vec3(0,0,-1),a.vm.xyz,top);contacts++;}float bottom=-pc.extentZ-(a.pr.z-a.pr.w);if(bottom>0){force+=wallForce(vec3(0,0,1),a.vm.xyz,bottom);contacts++;}
vec3 velocity=a.vm.xyz+force*(pc.dt/a.vm.w);vec3 position=a.pr.xyz+velocity*pc.dt;outputParticles[i].pr=vec4(position,a.pr.w);outputParticles[i].vm=vec4(velocity,a.vm.w);contactCounts[i]=contacts;}
)glsl";}
VkPipeline makePipeline(VkDevice d,VkPipelineLayout layout,const std::vector<std::uint32_t>&code,VkShaderModule&module){VkShaderModuleCreateInfo sm{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};sm.codeSize=code.size()*4;sm.pCode=code.data();check(vkCreateShaderModule(d,&sm,nullptr,&module),"vkCreateShaderModule");VkPipelineShaderStageCreateInfo stage{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;stage.module=module;stage.pName="main";VkComputePipelineCreateInfo ci{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};ci.stage=stage;ci.layout=layout;VkPipeline p=VK_NULL_HANDLE;check(vkCreateComputePipelines(d,VK_NULL_HANDLE,1,&ci,nullptr,&p),"vkCreateComputePipelines");return p;}
}
GpuResult stepVulkanDem(const field::ParticleSet&particles,const Settings&settings,double dt,const GpuSettings&gpu){GpuResult result;result.backend=backend::BackendKind::Vulkan;const auto start=std::chrono::steady_clock::now();VkInstance instance=VK_NULL_HANDLE;VkDevice device=VK_NULL_HANDLE;VkDescriptorSetLayout dsl=VK_NULL_HANDLE;VkPipelineLayout layout=VK_NULL_HANDLE;VkShaderModule binModule=VK_NULL_HANDLE,stepModule=VK_NULL_HANDLE;VkPipeline binPipeline=VK_NULL_HANDLE,stepPipeline=VK_NULL_HANDLE;VkDescriptorPool descriptorPool=VK_NULL_HANDLE;VkCommandPool commandPool=VK_NULL_HANDLE;VkFence fence=VK_NULL_HANDLE;std::array<Buffer,5>buf{};try{std::size_t n=particles.positions.size();if(n==0||particles.velocities.size()!=n||particles.radii.size()!=n||particles.masses.size()!=n)throw std::invalid_argument("GPU DEM particle arrays invalid");if(dt<=0||gpu.maximumParticlesPerCell==0)throw std::invalid_argument("GPU DEM settings invalid");double maxDiameter=0;for(std::size_t i=0;i<n;++i){if(particles.radii[i]<=0||particles.masses[i]<=0)throw std::invalid_argument("GPU DEM particle radius/mass invalid");maxDiameter=std::max(maxDiameter,2*particles.radii[i]);}double cellSize=maxDiameter;double ex=settings.drum.radius,ey=settings.drum.radius,ez=settings.drum.halfHeight;if(ex<=0||ez<=0)throw std::invalid_argument("GPU DEM drum invalid");auto dim=[&](double e){return std::max(1u,static_cast<std::uint32_t>(std::ceil(2*e/cellSize)));};std::uint32_t nx=dim(ex),ny=dim(ey),nz=dim(ez);std::uint64_t cellCount64=static_cast<std::uint64_t>(nx)*ny*nz;if(cellCount64>10000000ull)throw std::runtime_error("GPU DEM spatial grid exceeds safety limit");std::uint32_t cellCount=static_cast<std::uint32_t>(cellCount64);
VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="Vulkax GPU DEM";app.apiVersion=VK_API_VERSION_1_1;VkInstanceCreateInfo ici{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ici.pApplicationInfo=&app;check(vkCreateInstance(&ici,nullptr,&instance),"vkCreateInstance");std::uint32_t pcnt=0;check(vkEnumeratePhysicalDevices(instance,&pcnt,nullptr),"vkEnumeratePhysicalDevices");if(!pcnt)throw std::runtime_error("no Vulkan devices");std::vector<VkPhysicalDevice>phys(pcnt);check(vkEnumeratePhysicalDevices(instance,&pcnt,phys.data()),"vkEnumeratePhysicalDevices");VkPhysicalDevice physical=VK_NULL_HANDLE;std::uint32_t qfam=0;for(auto p:phys){std::uint32_t qc=0;vkGetPhysicalDeviceQueueFamilyProperties(p,&qc,nullptr);std::vector<VkQueueFamilyProperties>qs(qc);vkGetPhysicalDeviceQueueFamilyProperties(p,&qc,qs.data());for(std::uint32_t q=0;q<qc;++q)if(qs[q].queueFlags&VK_QUEUE_COMPUTE_BIT){physical=p;qfam=q;break;}if(physical)break;}if(!physical)throw std::runtime_error("no Vulkan compute queue");VkPhysicalDeviceProperties prop{};vkGetPhysicalDeviceProperties(physical,&prop);result.deviceName=prop.deviceName;float priority=1;VkDeviceQueueCreateInfo qci{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qci.queueFamilyIndex=qfam;qci.queueCount=1;qci.pQueuePriorities=&priority;VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};dci.queueCreateInfoCount=1;dci.pQueueCreateInfos=&qci;check(vkCreateDevice(physical,&dci,nullptr,&device),"vkCreateDevice");VkQueue queue=VK_NULL_HANDLE;vkGetDeviceQueue(device,qfam,0,&queue);
std::array<VkDescriptorSetLayoutBinding,5>bindings{};for(std::uint32_t i=0;i<5;++i){bindings[i].binding=i;bindings[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;bindings[i].descriptorCount=1;bindings[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}VkDescriptorSetLayoutCreateInfo dl{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};dl.bindingCount=5;dl.pBindings=bindings.data();check(vkCreateDescriptorSetLayout(device,&dl,nullptr,&dsl),"vkCreateDescriptorSetLayout");VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(Push)};VkPipelineLayoutCreateInfo pli{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pli.setLayoutCount=1;pli.pSetLayouts=&dsl;pli.pushConstantRangeCount=1;pli.pPushConstantRanges=&range;check(vkCreatePipelineLayout(device,&pli,nullptr,&layout),"vkCreatePipelineLayout");auto binCode=compile(binShader(),"bin"),stepCode=compile(stepShader(),"step");binPipeline=makePipeline(device,layout,binCode,binModule);stepPipeline=makePipeline(device,layout,stepCode,stepModule);
VkDeviceSize particleBytes=n*sizeof(ParticleGpu),countBytes=static_cast<VkDeviceSize>(cellCount)*4,indexBytes=static_cast<VkDeviceSize>(cellCount)*gpu.maximumParticlesPerCell*4,contactBytes=n*4;buf[0]=makeBuffer(physical,device,particleBytes);buf[1]=makeBuffer(physical,device,particleBytes);buf[2]=makeBuffer(physical,device,countBytes);buf[3]=makeBuffer(physical,device,indexBytes);buf[4]=makeBuffer(physical,device,contactBytes);auto*packed=static_cast<ParticleGpu*>(buf[0].mapped);for(std::size_t i=0;i<n;++i)packed[i]={static_cast<float>(particles.positions[i].x),static_cast<float>(particles.positions[i].y),static_cast<float>(particles.positions[i].z),static_cast<float>(particles.radii[i]),static_cast<float>(particles.velocities[i].x),static_cast<float>(particles.velocities[i].y),static_cast<float>(particles.velocities[i].z),static_cast<float>(particles.masses[i])};
VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,5};VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=1;dpi.poolSizeCount=1;dpi.pPoolSizes=&ps;check(vkCreateDescriptorPool(device,&dpi,nullptr,&descriptorPool),"vkCreateDescriptorPool");VkDescriptorSetAllocateInfo asi{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};asi.descriptorPool=descriptorPool;asi.descriptorSetCount=1;asi.pSetLayouts=&dsl;VkDescriptorSet set=VK_NULL_HANDLE;check(vkAllocateDescriptorSets(device,&asi,&set),"vkAllocateDescriptorSets");std::array<VkDescriptorBufferInfo,5>infos{};for(std::size_t i=0;i<5;++i)infos[i]={buf[i].buffer,0,buf[i].size};std::array<VkWriteDescriptorSet,5>writes{};for(std::uint32_t i=0;i<5;++i){writes[i]={VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};writes[i].dstSet=set;writes[i].dstBinding=i;writes[i].descriptorCount=1;writes[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;writes[i].pBufferInfo=&infos[i];}vkUpdateDescriptorSets(device,5,writes.data(),0,nullptr);
Push push;push.particleCount=static_cast<std::uint32_t>(n);push.cellCount=cellCount;push.nx=nx;push.ny=ny;push.nz=nz;push.capacity=gpu.maximumParticlesPerCell;push.dt=static_cast<float>(dt);push.cellSize=static_cast<float>(cellSize);push.extentX=static_cast<float>(ex);push.extentY=static_cast<float>(ey);push.extentZ=static_cast<float>(ez);push.omega=static_cast<float>(settings.drum.angularVelocity);push.gx=static_cast<float>(settings.gravity.x);push.gy=static_cast<float>(settings.gravity.y);push.gz=static_cast<float>(settings.gravity.z);push.kn=static_cast<float>(settings.particleMaterial.normalStiffness);push.damping=static_cast<float>(settings.particleMaterial.normalDamping);push.tangentialDamping=static_cast<float>(settings.particleMaterial.tangentialDamping);push.friction=static_cast<float>(settings.particleMaterial.friction);push.wallKn=static_cast<float>(settings.drum.wallMaterial.normalStiffness);push.wallDamping=static_cast<float>(settings.drum.wallMaterial.normalDamping);push.wallTangentialDamping=static_cast<float>(settings.drum.wallMaterial.tangentialDamping);push.wallFriction=static_cast<float>(settings.drum.wallMaterial.friction);
VkCommandPoolCreateInfo cpi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};cpi.queueFamilyIndex=qfam;check(vkCreateCommandPool(device,&cpi,nullptr,&commandPool),"vkCreateCommandPool");VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};cai.commandPool=commandPool;cai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;cai.commandBufferCount=1;VkCommandBuffer cmd=VK_NULL_HANDLE;check(vkAllocateCommandBuffers(device,&cai,&cmd),"vkAllocateCommandBuffers");VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};check(vkBeginCommandBuffer(cmd,&bi),"vkBeginCommandBuffer");vkCmdFillBuffer(cmd,buf[2].buffer,0,VK_WHOLE_SIZE,0);vkCmdFillBuffer(cmd,buf[4].buffer,0,VK_WHOLE_SIZE,0);VkMemoryBarrier transfer{VK_STRUCTURE_TYPE_MEMORY_BARRIER};transfer.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;transfer.dstAccessMask=VK_ACCESS_SHADER_READ_BIT|VK_ACCESS_SHADER_WRITE_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,1,&transfer,0,nullptr,0,nullptr);vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,layout,0,1,&set,0,nullptr);vkCmdPushConstants(cmd,layout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(Push),&push);vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,binPipeline);vkCmdDispatch(cmd,(push.particleCount+127)/128,1,1);VkMemoryBarrier binBarrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};binBarrier.srcAccessMask=VK_ACCESS_SHADER_WRITE_BIT;binBarrier.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,1,&binBarrier,0,nullptr,0,nullptr);vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,stepPipeline);vkCmdDispatch(cmd,(push.particleCount+127)/128,1,1);VkMemoryBarrier host{VK_STRUCTURE_TYPE_MEMORY_BARRIER};host.srcAccessMask=VK_ACCESS_SHADER_WRITE_BIT;host.dstAccessMask=VK_ACCESS_HOST_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,1,&host,0,nullptr,0,nullptr);check(vkEndCommandBuffer(cmd),"vkEndCommandBuffer");VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};check(vkCreateFence(device,&fi,nullptr,&fence),"vkCreateFence");VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&cmd;check(vkQueueSubmit(queue,1,&si,fence),"vkQueueSubmit");check(vkWaitForFences(device,1,&fence,VK_TRUE,UINT64_MAX),"vkWaitForFences");
result.particles.positions.resize(n);result.particles.velocities.resize(n);result.particles.radii.resize(n);result.particles.masses.resize(n);auto*out=static_cast<const ParticleGpu*>(buf[1].mapped);for(std::size_t i=0;i<n;++i){result.particles.positions[i]={out[i].px,out[i].py,out[i].pz};result.particles.velocities[i]={out[i].vx,out[i].vy,out[i].vz};result.particles.radii[i]=out[i].radius;result.particles.masses[i]=out[i].mass;}auto*counts=static_cast<const std::uint32_t*>(buf[2].mapped);for(std::uint32_t c=0;c<cellCount;++c)if(counts[c]>gpu.maximumParticlesPerCell)++result.overflowingCells;auto*contacts=static_cast<const std::uint32_t*>(buf[4].mapped);std::uint64_t sum=0;for(std::size_t i=0;i<n;++i)sum+=contacts[i];result.particleContacts=static_cast<std::size_t>(sum/2);result.ok=result.overflowingCells==0;if(!result.ok)result.diagnostic="spatial hash cell capacity overflowed; increase maximumParticlesPerCell or reduce particle polydispersity";
}catch(const std::exception&e){result.diagnostic=e.what();}if(device)vkDeviceWaitIdle(device);if(fence)vkDestroyFence(device,fence,nullptr);if(commandPool)vkDestroyCommandPool(device,commandPool,nullptr);if(descriptorPool)vkDestroyDescriptorPool(device,descriptorPool,nullptr);for(auto&b:buf)if(device)destroy(device,b);if(binPipeline)vkDestroyPipeline(device,binPipeline,nullptr);if(stepPipeline)vkDestroyPipeline(device,stepPipeline,nullptr);if(binModule)vkDestroyShaderModule(device,binModule,nullptr);if(stepModule)vkDestroyShaderModule(device,stepModule,nullptr);if(layout)vkDestroyPipelineLayout(device,layout,nullptr);if(dsl)vkDestroyDescriptorSetLayout(device,dsl,nullptr);if(device)vkDestroyDevice(device,nullptr);if(instance)vkDestroyInstance(instance,nullptr);result.wallMilliseconds=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();return result;}
} // namespace vulkax::physics::dem
