#include "vulkax/visualization/export.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <limits>
#include <stdexcept>

namespace vulkax::visualization {
namespace {
Rgba8 lerp(Rgba8 a,Rgba8 b,double t){auto c=[&](std::uint8_t x,std::uint8_t y){return static_cast<std::uint8_t>(std::lround((1-t)*x+t*y));};return{c(a.r,b.r),c(a.g,b.g),c(a.b,b.b),255};}
}
Rgba8 mapScientificColor(double x,ColorMap map){x=std::clamp(x,0.0,1.0);if(map==ColorMap::Diverging){static constexpr std::array<Rgba8,3>a{{{49,54,149,255},{247,247,247,255},{165,0,38,255}}};if(x<0.5)return lerp(a[0],a[1],x*2);return lerp(a[1],a[2],(x-0.5)*2);}static constexpr std::array<Rgba8,5>a{{{68,1,84,255},{59,82,139,255},{33,145,140,255},{94,201,98,255},{253,231,37,255}}};double f=x*4;std::size_t i=std::min<std::size_t>(static_cast<std::size_t>(f),3);return lerp(a[i],a[i+1],f-i);}
Image renderScalarSliceZ(const field::ScalarField&f,std::uint32_t z,double mn,double mx,ColorMap map,std::uint32_t scale){if(f.values.size()!=f.grid.cellCount()||z>=f.grid.nz||!(mn<mx)||scale==0)throw std::invalid_argument("invalid scalar slice request");Image img{f.grid.nx*scale,f.grid.ny*scale,std::vector<Rgba8>(static_cast<std::size_t>(f.grid.nx)*scale*f.grid.ny*scale)};for(std::uint32_t y=0;y<f.grid.ny;++y)for(std::uint32_t x=0;x<f.grid.nx;++x){double t=(f.values[f.grid.index(x,y,z)]-mn)/(mx-mn);auto color=mapScientificColor(t,map);for(std::uint32_t sy=0;sy<scale;++sy)for(std::uint32_t sx=0;sx<scale;++sx)img.pixels[static_cast<std::size_t>(y*scale+sy)*img.width+x*scale+sx]=color;}return img;}
Image renderParticlesOrthographic(const field::ParticleSet&p,std::uint32_t w,std::uint32_t h,double extent,std::span<const double>scalar){const auto n=p.positions.size();if(w==0||h==0||extent<=0||p.radii.size()!=n||(!scalar.empty()&&scalar.size()!=n))throw std::invalid_argument("invalid particle render request");Image img{w,h,std::vector<Rgba8>(static_cast<std::size_t>(w)*h,{10,12,18,255})};std::vector<double>depth(img.pixels.size(),-std::numeric_limits<double>::infinity());double minS=0,maxS=1;if(!scalar.empty()){auto [lo,hi]=std::minmax_element(scalar.begin(),scalar.end());minS=*lo;maxS=*hi;if(!(minS<maxS))maxS=minS+1;}for(std::size_t i=0;i<n;++i){double fx=(p.positions[i].x/extent*0.5+0.5)*w,fy=(0.5-p.positions[i].y/extent*0.5)*h;int cx=static_cast<int>(fx),cy=static_cast<int>(fy);int radius=std::max(1,static_cast<int>(std::ceil(p.radii[i]/(2*extent)*w)));double t=scalar.empty()?0.65:(scalar[i]-minS)/(maxS-minS);auto base=mapScientificColor(t);for(int yy=cy-radius;yy<=cy+radius;++yy)for(int xx=cx-radius;xx<=cx+radius;++xx){if(xx<0||yy<0||xx>=static_cast<int>(w)||yy>=static_cast<int>(h))continue;double dx=static_cast<double>(xx-cx)/radius,dy=static_cast<double>(yy-cy)/radius;double rr=dx*dx+dy*dy;if(rr>1)continue;double sphere=std::sqrt(std::max(0.0,1-rr));double z=p.positions[i].z+p.radii[i]*sphere;auto pixel=static_cast<std::size_t>(yy)*w+static_cast<std::size_t>(xx);if(z<=depth[pixel])continue;depth[pixel]=z;double light=0.35+0.65*sphere;img.pixels[pixel]={static_cast<std::uint8_t>(std::clamp(base.r*light,0.0,255.0)),static_cast<std::uint8_t>(std::clamp(base.g*light,0.0,255.0)),static_cast<std::uint8_t>(std::clamp(base.b*light,0.0,255.0)),255};}}return img;}
void writePpm(const Image&i,const std::filesystem::path&path){if(i.pixels.size()!=static_cast<std::size_t>(i.width)*i.height)throw std::invalid_argument("image pixel count mismatch");std::ofstream out(path,std::ios::binary);if(!out)throw std::runtime_error("cannot open PPM output");out<<"P6\n"<<i.width<<" "<<i.height<<"\n255\n";for(auto p:i.pixels){out.put(static_cast<char>(p.r));out.put(static_cast<char>(p.g));out.put(static_cast<char>(p.b));}}
void writeObj(const field::TriangleMesh&m,const std::filesystem::path&path){std::ofstream out(path);if(!out)throw std::runtime_error("cannot open OBJ output");for(auto v:m.vertices)out<<"v "<<v.x<<" "<<v.y<<" "<<v.z<<"\n";for(auto t:m.triangles){if(t[0]>=m.vertices.size()||t[1]>=m.vertices.size()||t[2]>=m.vertices.size())throw std::invalid_argument("OBJ triangle index invalid");out<<"f "<<t[0]+1<<" "<<t[1]+1<<" "<<t[2]+1<<"\n";}}
} // namespace vulkax::visualization
