#include "vulkax/verify/convergence.hpp"

#include <algorithm>
#include <cmath>

namespace vulkax::verify {
ConvergenceEstimate estimateRichardson(const std::vector<ConvergenceSample>& input){ConvergenceEstimate out;if(input.size()<3){out.diagnostic="at least three resolutions are required";return out;}auto s=input;std::sort(s.begin(),s.end(),[](const auto&a,const auto&b){return a.characteristicSpacing>b.characteristicSpacing;});const auto&a=s[s.size()-3],&b=s[s.size()-2],&c=s[s.size()-1];if(a.characteristicSpacing<=0||b.characteristicSpacing<=0||c.characteristicSpacing<=0){out.diagnostic="resolution spacing must be positive";return out;}double r1=a.characteristicSpacing/b.characteristicSpacing,r2=b.characteristicSpacing/c.characteristicSpacing;if(std::abs(r1-r2)>0.05*std::max(r1,r2)||r1<=1.0){out.diagnostic="Richardson estimate currently requires approximately uniform refinement ratios";return out;}double e1=std::abs(a.observable-b.observable),e2=std::abs(b.observable-c.observable);if(e1<=1e-15||e2<=1e-15){if(e1<=1e-15&&e2<=1e-15){out.valid=true;out.observedOrder=0;out.extrapolatedValue=c.observable;out.absoluteUncertainty=0;out.relativeUncertainty=0;return out;}out.diagnostic="differences are too small for a stable observed-order estimate";return out;}double p=std::log(e1/e2)/std::log(r1);if(!std::isfinite(p)||p<=0){out.diagnostic="sequence is not monotonically converging";return out;}double denom=std::pow(r1,p)-1.0;if(std::abs(denom)<1e-14){out.diagnostic="Richardson denominator is singular";return out;}double extrap=c.observable+(c.observable-b.observable)/denom;double uncertainty=std::abs(extrap-c.observable);out.valid=true;out.observedOrder=p;out.extrapolatedValue=extrap;out.absoluteUncertainty=uncertainty;out.relativeUncertainty=uncertainty/std::max(std::abs(extrap),1e-15);return out;}
ResultCertificate certificateFromConvergence(std::uint64_t ph,std::uint64_t sh,std::string backend,std::string device,const ConvergenceEstimate&conv,double requested,double residual,double residualTol,double conservation,double conservationTol){ResultCertificate c;c.problemHash=ph;c.solverHash=sh;c.backend=std::move(backend);c.device=std::move(device);c.criteria.push_back({"solver residual",residual,residualTol,CriterionRelation::LessEqual,true});c.criteria.push_back({"conservation error",conservation,conservationTol,CriterionRelation::LessEqual,true});if(conv.valid)c.criteria.push_back({"discretization uncertainty",conv.relativeUncertainty,requested,CriterionRelation::LessEqual,true});else{c.criteria.push_back({"discretization uncertainty",1.0,requested,CriterionRelation::LessEqual,true});c.notes.push_back(conv.diagnostic);}c.updateTrustState(conv.valid);return c;}
} // namespace vulkax::verify
