#include "vulkax/sim/simulation_graph.hpp"

#include <vulkan/vulkan.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
struct alignas(16) StepParameters { uint32_t width, height; float coefficient, padding; };
static_assert(sizeof(StepParameters) == 16);
struct Buffer { VkBuffer buffer = VK_NULL_HANDLE; VkDeviceMemory memory = VK_NULL_HANDLE; };
void check(VkResult value, const char* name) { if (value != VK_SUCCESS) throw std::runtime_error(std::string{name} + ": " + std::to_string(value)); }
uint32_t memoryType(VkPhysicalDevice device, uint32_t mask) {
  VkPhysicalDeviceMemoryProperties props{}; vkGetPhysicalDeviceMemoryProperties(device, &props);
  for (uint32_t i = 0; i < props.memoryTypeCount; ++i)
    if ((mask & (1u << i)) && (props.memoryTypes[i].propertyFlags & (VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) == (VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) return i;
  throw std::runtime_error("host-visible coherent memory unavailable");
}
Buffer buffer(VkPhysicalDevice physical, VkDevice device, VkDeviceSize size, VkBufferUsageFlags usage) {
  VkBufferCreateInfo info{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO}; info.size = size; info.usage = usage; info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  Buffer result{}; check(vkCreateBuffer(device, &info, nullptr, &result.buffer), "vkCreateBuffer");
  VkMemoryRequirements requirements{}; vkGetBufferMemoryRequirements(device, result.buffer, &requirements);
  VkMemoryAllocateInfo allocation{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO}; allocation.allocationSize = requirements.size; allocation.memoryTypeIndex = memoryType(physical, requirements.memoryTypeBits);
  check(vkAllocateMemory(device, &allocation, nullptr, &result.memory), "vkAllocateMemory"); check(vkBindBufferMemory(device, result.buffer, result.memory, 0), "vkBindBufferMemory"); return result;
}
void upload(VkDevice device, VkDeviceMemory memory, const void* source, size_t bytes) { void* mapped{}; check(vkMapMemory(device, memory, 0, bytes, 0, &mapped), "vkMapMemory"); std::memcpy(mapped, source, bytes); vkUnmapMemory(device, memory); }
std::vector<char> binary(const std::filesystem::path& path) { std::ifstream file(path, std::ios::binary | std::ios::ate); if (!file) throw std::runtime_error("shader missing: " + path.string()); std::vector<char> result(static_cast<size_t>(file.tellg())); file.seekg(0); file.read(result.data(), result.size()); return result; }
bool portability() { uint32_t count{}; vkEnumerateInstanceExtensionProperties(nullptr, &count, nullptr); std::vector<VkExtensionProperties> properties(count); vkEnumerateInstanceExtensionProperties(nullptr, &count, properties.data()); return std::any_of(properties.begin(), properties.end(), [](const auto& value) { return std::string{value.extensionName} == VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME; }); }
}

int main(int argc, char** argv) {
  try {
    uint32_t steps = 32; std::filesystem::path output = "docs/results/physics_studio_current/gpu_wave_simulation";
    for (int i = 1; i < argc; ++i) { const std::string option{argv[i]}; if (option == "--steps" && i + 1 < argc) steps = std::stoul(argv[++i]); else if (option == "--output" && i + 1 < argc) output = argv[++i]; else throw std::invalid_argument("usage: vulkax-sim-compute [--steps N --output PATH]"); }
    constexpr uint32_t width = 64, height = 64; constexpr float timestep = 1.0f / 120.0f, spacing = 0.1f;
    vulkax::sim::SimulationGraph cpu{{vulkax::sim::SimulationKind::Wave, width, height, timestep, spacing, 1337}};
    const auto initial = cpu.primaryField(); cpu.step(steps);
    VkApplicationInfo application{VK_STRUCTURE_TYPE_APPLICATION_INFO}; application.pApplicationName = "Vulkax GPU Wave Simulation"; application.apiVersion = VK_API_VERSION_1_1;
    VkInstanceCreateInfo instanceInfo{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO}; instanceInfo.pApplicationInfo = &application; std::vector<const char*> extensions;
    if (portability()) { extensions.push_back(VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME); instanceInfo.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR; }
    instanceInfo.enabledExtensionCount = static_cast<uint32_t>(extensions.size()); instanceInfo.ppEnabledExtensionNames = extensions.data(); VkInstance instance{}; check(vkCreateInstance(&instanceInfo, nullptr, &instance), "vkCreateInstance");
    uint32_t count{}; check(vkEnumeratePhysicalDevices(instance, &count, nullptr), "vkEnumeratePhysicalDevices"); std::vector<VkPhysicalDevice> devices(count); check(vkEnumeratePhysicalDevices(instance, &count, devices.data()), "vkEnumeratePhysicalDevices"); VkPhysicalDevice physical{}; uint32_t family{};
    for (const auto candidate : devices) { uint32_t familiesCount{}; vkGetPhysicalDeviceQueueFamilyProperties(candidate, &familiesCount, nullptr); std::vector<VkQueueFamilyProperties> families(familiesCount); vkGetPhysicalDeviceQueueFamilyProperties(candidate, &familiesCount, families.data()); for (uint32_t i = 0; i < familiesCount; ++i) if (families[i].queueFlags & VK_QUEUE_COMPUTE_BIT) { physical = candidate; family = i; break; } if (physical) break; }
    if (!physical) throw std::runtime_error("compute queue unavailable"); VkPhysicalDeviceProperties properties{}; vkGetPhysicalDeviceProperties(physical, &properties);
    const float priority = 1.0f; VkDeviceQueueCreateInfo queueInfo{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO}; queueInfo.queueFamilyIndex = family; queueInfo.queueCount = 1; queueInfo.pQueuePriorities = &priority; VkDeviceCreateInfo deviceInfo{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO}; deviceInfo.queueCreateInfoCount = 1; deviceInfo.pQueueCreateInfos = &queueInfo; VkDevice device{}; check(vkCreateDevice(physical, &deviceInfo, nullptr, &device), "vkCreateDevice"); VkQueue queue{}; vkGetDeviceQueue(device, family, 0, &queue);
    const VkDeviceSize bytes = static_cast<VkDeviceSize>(width) * height * sizeof(float); Buffer previous = buffer(physical, device, bytes, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT), current = buffer(physical, device, bytes, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT), next = buffer(physical, device, bytes, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT), uniform = buffer(physical, device, sizeof(StepParameters), VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT); upload(device, previous.memory, initial.data(), bytes); upload(device, current.memory, initial.data(), bytes); const StepParameters parameters{width, height, std::pow(timestep / spacing, 2.0f), 0.0f}; upload(device, uniform.memory, &parameters, sizeof(parameters));
    VkDescriptorSetLayoutBinding bindings[4]{}; for (uint32_t i = 0; i < 3; ++i) bindings[i] = {i, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr}; bindings[3] = {3, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr}; VkDescriptorSetLayoutCreateInfo descriptorLayoutInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO}; descriptorLayoutInfo.bindingCount = 4; descriptorLayoutInfo.pBindings = bindings; VkDescriptorSetLayout descriptorLayout{}; check(vkCreateDescriptorSetLayout(device, &descriptorLayoutInfo, nullptr, &descriptorLayout), "vkCreateDescriptorSetLayout"); VkPipelineLayoutCreateInfo pipelineLayoutInfo{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO}; pipelineLayoutInfo.setLayoutCount = 1; pipelineLayoutInfo.pSetLayouts = &descriptorLayout; VkPipelineLayout pipelineLayout{}; check(vkCreatePipelineLayout(device, &pipelineLayoutInfo, nullptr, &pipelineLayout), "vkCreatePipelineLayout");
    const auto code = binary(std::filesystem::path{ENGINE_DIR} / "shaders/vulkax_wave_step.comp.spv"); VkShaderModuleCreateInfo shaderInfo{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO}; shaderInfo.codeSize = code.size(); shaderInfo.pCode = reinterpret_cast<const uint32_t*>(code.data()); VkShaderModule shader{}; check(vkCreateShaderModule(device, &shaderInfo, nullptr, &shader), "vkCreateShaderModule"); VkComputePipelineCreateInfo pipelineInfo{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO}; pipelineInfo.stage = {VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, nullptr, 0, VK_SHADER_STAGE_COMPUTE_BIT, shader, "main", nullptr}; pipelineInfo.layout = pipelineLayout; VkPipeline pipeline{}; check(vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr, &pipeline), "vkCreateComputePipelines");
    VkDescriptorPoolSize sizes[2]{{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 3}, {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1}}; VkDescriptorPoolCreateInfo poolInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO}; poolInfo.maxSets = 1; poolInfo.poolSizeCount = 2; poolInfo.pPoolSizes = sizes; VkDescriptorPool pool{}; check(vkCreateDescriptorPool(device, &poolInfo, nullptr, &pool), "vkCreateDescriptorPool"); VkDescriptorSetAllocateInfo setInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO}; setInfo.descriptorPool = pool; setInfo.descriptorSetCount = 1; setInfo.pSetLayouts = &descriptorLayout; VkDescriptorSet set{}; check(vkAllocateDescriptorSets(device, &setInfo, &set), "vkAllocateDescriptorSets");
    VkCommandPoolCreateInfo commandPoolInfo{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO}; commandPoolInfo.queueFamilyIndex = family; VkCommandPool commandPool{}; check(vkCreateCommandPool(device, &commandPoolInfo, nullptr, &commandPool), "vkCreateCommandPool"); VkCommandBufferAllocateInfo commandInfo{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO}; commandInfo.commandPool = commandPool; commandInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; commandInfo.commandBufferCount = 1; VkCommandBuffer command{}; check(vkAllocateCommandBuffers(device, &commandInfo, &command), "vkAllocateCommandBuffers");
    for (uint32_t step = 0; step < steps; ++step) { VkDescriptorBufferInfo infos[4]{{current.buffer, 0, bytes}, {previous.buffer, 0, bytes}, {next.buffer, 0, bytes}, {uniform.buffer, 0, sizeof(parameters)}}; VkWriteDescriptorSet writes[4]{}; for (uint32_t i = 0; i < 4; ++i) writes[i] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, set, i, 0, 1, i == 3 ? VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER : VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &infos[i], nullptr}; vkUpdateDescriptorSets(device, 4, writes, 0, nullptr); VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO}; check(vkBeginCommandBuffer(command, &begin), "vkBeginCommandBuffer"); vkCmdBindPipeline(command, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline); vkCmdBindDescriptorSets(command, VK_PIPELINE_BIND_POINT_COMPUTE, pipelineLayout, 0, 1, &set, 0, nullptr); vkCmdDispatch(command, (width + 15) / 16, (height + 15) / 16, 1); check(vkEndCommandBuffer(command), "vkEndCommandBuffer"); VkFenceCreateInfo fenceInfo{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO}; VkFence fence{}; check(vkCreateFence(device, &fenceInfo, nullptr, &fence), "vkCreateFence"); VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO}; submit.commandBufferCount = 1; submit.pCommandBuffers = &command; check(vkQueueSubmit(queue, 1, &submit, fence), "vkQueueSubmit"); check(vkWaitForFences(device, 1, &fence, VK_TRUE, UINT64_MAX), "vkWaitForFences"); vkDestroyFence(device, fence, nullptr); vkResetCommandBuffer(command, 0); std::swap(previous, current); std::swap(current, next); }
    std::vector<float> result(width * height); void* mapped{}; check(vkMapMemory(device, current.memory, 0, bytes, 0, &mapped), "vkMapMemory result"); std::memcpy(result.data(), mapped, bytes); vkUnmapMemory(device, current.memory); double mse = 0.0, maximum = 0.0; for (size_t i = 0; i < result.size(); ++i) { const double error = std::abs(result[i] - cpu.primaryField()[i]); mse += error * error; maximum = std::max(maximum, error); } mse /= result.size(); std::filesystem::create_directories(output); std::ofstream report{output / "gpu_wave_simulation_agreement.json"}; report << "{\n  \"measurement_class\": \"vulkan_ping_pong_compute_readback\",\n  \"device\": \"" << properties.deviceName << "\",\n  \"steps\": " << steps << ",\n  \"mse\": " << mse << ",\n  \"max_error\": " << maximum << "\n}\n"; std::cout << "Vulkan wave simulation " << properties.deviceName << " steps=" << steps << " MSE=" << mse << " max error=" << maximum << '\n';
    vkDestroyCommandPool(device, commandPool, nullptr); vkDestroyDescriptorPool(device, pool, nullptr); vkDestroyPipeline(device, pipeline, nullptr); vkDestroyShaderModule(device, shader, nullptr); vkDestroyPipelineLayout(device, pipelineLayout, nullptr); vkDestroyDescriptorSetLayout(device, descriptorLayout, nullptr); for (const auto value : {previous, current, next, uniform}) { vkDestroyBuffer(device, value.buffer, nullptr); vkFreeMemory(device, value.memory, nullptr); } vkDestroyDevice(device, nullptr); vkDestroyInstance(instance, nullptr); return maximum < 1e-5 ? 0 : 3;
  } catch (const std::exception& error) { std::cerr << "vulkax-sim-compute: " << error.what() << '\n'; return 1; }
}
