#include "vulkax/solvers/mac3d.hpp"

#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace vulkax::solvers {

MacGrid3D::MacGrid3D(std::size_t nx,std::size_t ny,std::size_t nz,double dx,double dy,double dz):nx_(nx),ny_(ny),nz_(nz),dx_(dx),dy_(dy),dz_(dz),u_((nx+1)*ny*nz),v_(nx*(ny+1)*nz),w_(nx*ny*(nz+1)),pressure_(nx*ny*nz),solid_(nx*ny*nz){if(nx<2||ny<2||nz<2||dx<=0||dy<=0||dz<=0)throw std::invalid_argument("invalid MAC grid");}
std::size_t MacGrid3D::cellIndex(std::size_t x,std::size_t y,std::size_t z)const{if(x>=nx_||y>=ny_||z>=nz_)throw std::out_of_range("MAC cell index");return(z*ny_+y)*nx_+x;}
std::size_t MacGrid3D::uIndex(std::size_t x,std::size_t y,std::size_t z)const{if(x>nx_||y>=ny_||z>=nz_)throw std::out_of_range("MAC u index");return(z*ny_+y)*(nx_+1)+x;}
std::size_t MacGrid3D::vIndex(std::size_t x,std::size_t y,std::size_t z)const{if(x>=nx_||y>ny_||z>=nz_)throw std::out_of_range("MAC v index");return(z*(ny_+1)+y)*nx_+x;}
std::size_t MacGrid3D::wIndex(std::size_t x,std::size_t y,std::size_t z)const{if(x>=nx_||y>=ny_||z>nz_)throw std::out_of_range("MAC w index");return(z*ny_+y)*nx_+x;}
double&MacGrid3D::u(std::size_t x,std::size_t y,std::size_t z){return u_[uIndex(x,y,z)];}double&MacGrid3D::v(std::size_t x,std::size_t y,std::size_t z){return v_[vIndex(x,y,z)];}double&MacGrid3D::w(std::size_t x,std::size_t y,std::size_t z){return w_[wIndex(x,y,z)];}double&MacGrid3D::pressure(std::size_t x,std::size_t y,std::size_t z){return pressure_[cellIndex(x,y,z)];}std::uint8_t&MacGrid3D::solid(std::size_t x,std::size_t y,std::size_t z){return solid_[cellIndex(x,y,z)];}
double MacGrid3D::u(std::size_t x,std::size_t y,std::size_t z)const{return u_[uIndex(x,y,z)];}double MacGrid3D::v(std::size_t x,std::size_t y,std::size_t z)const{return v_[vIndex(x,y,z)];}double MacGrid3D::w(std::size_t x,std::size_t y,std::size_t z)const{return w_[wIndex(x,y,z)];}double MacGrid3D::pressure(std::size_t x,std::size_t y,std::size_t z)const{return pressure_[cellIndex(x,y,z)];}bool MacGrid3D::solid(std::size_t x,std::size_t y,std::size_t z)const{return solid_[cellIndex(x,y,z)]!=0;}
void MacGrid3D::setSolidMask(const geometry::VoxelMask&mask){if(mask.nx!=nx_||mask.ny!=ny_||mask.nz!=nz_)throw std::invalid_argument("voxel mask dimensions do not match MAC grid");solid_=mask.solid;}

namespace {
double divAt(const MacGrid3D&g,std::size_t x,std::size_t y,std::size_t z){if(g.solid(x,y,z))return 0;return(g.u(x+1,y,z)-g.u(x,y,z))/g.dx()+(g.v(x,y+1,z)-g.v(x,y,z))/g.dy()+(g.w(x,y,z+1)-g.w(x,y,z))/g.dz();}
void enforceSolidFaces(MacGrid3D&g){for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y){g.u(0,y,z)=0;g.u(g.nx(),y,z)=0;}for(std::size_t z=0;z<g.nz();++z)for(std::size_t x=0;x<g.nx();++x){g.v(x,0,z)=0;g.v(x,g.ny(),z)=0;}for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x){g.w(x,y,0)=0;g.w(x,y,g.nz())=0;}for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=1;x<g.nx();++x)if(g.solid(x-1,y,z)||g.solid(x,y,z))g.u(x,y,z)=0;for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=1;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x)if(g.solid(x,y-1,z)||g.solid(x,y,z))g.v(x,y,z)=0;for(std::size_t z=1;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x)if(g.solid(x,y,z-1)||g.solid(x,y,z))g.w(x,y,z)=0;}
}

double divergenceL2(const MacGrid3D&g){double sum=0;std::size_t count=0;for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x)if(!g.solid(x,y,z)){const double d=divAt(g,x,y,z);sum+=d*d;++count;}return count?std::sqrt(sum/static_cast<double>(count)):0;}

MacDiagnostics projectMacGrid(MacGrid3D&g,const MacProjectionConfig&config){if(config.dt<=0||config.density<=0||config.pressureIterations==0)throw std::invalid_argument("invalid MAC projection config");enforceSolidFaces(g);MacDiagnostics out;out.divergenceL2Before=divergenceL2(g);std::vector<double> next(g.nx()*g.ny()*g.nz(),0.0);const double wx=1/(g.dx()*g.dx()),wy=1/(g.dy()*g.dy()),wz=1/(g.dz()*g.dz());auto p=[&](long long x,long long y,long long z,std::size_t cx,std::size_t cy,std::size_t cz){if(x<0||y<0||z<0||x>=static_cast<long long>(g.nx())||y>=static_cast<long long>(g.ny())||z>=static_cast<long long>(g.nz())||g.solid(static_cast<std::size_t>(x),static_cast<std::size_t>(y),static_cast<std::size_t>(z)))return g.pressure(cx,cy,cz);return g.pressure(static_cast<std::size_t>(x),static_cast<std::size_t>(y),static_cast<std::size_t>(z));};for(std::size_t iter=0;iter<config.pressureIterations;++iter){for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x){const std::size_t idx=(z*g.ny()+y)*g.nx()+x;if(g.solid(x,y,z)){next[idx]=0;continue;}const double rhs=config.density/config.dt*divAt(g,x,y,z);const double neighbor=wx*(p(static_cast<long long>(x)-1,y,z,x,y,z)+p(x+1,y,z,x,y,z))+wy*(p(x,static_cast<long long>(y)-1,z,x,y,z)+p(x,y+1,z,x,y,z))+wz*(p(x,y,static_cast<long long>(z)-1,x,y,z)+p(x,y,z+1,x,y,z));next[idx]=(neighbor-rhs)/(2*(wx+wy+wz));}for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x)g.pressure(x,y,z)=next[(z*g.ny()+y)*g.nx()+x];}
    for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=1;x<g.nx();++x)if(!g.solid(x-1,y,z)&&!g.solid(x,y,z))g.u(x,y,z)-=config.dt/config.density*(g.pressure(x,y,z)-g.pressure(x-1,y,z))/g.dx();for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=1;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x)if(!g.solid(x,y-1,z)&&!g.solid(x,y,z))g.v(x,y,z)-=config.dt/config.density*(g.pressure(x,y,z)-g.pressure(x,y-1,z))/g.dy();for(std::size_t z=1;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x)if(!g.solid(x,y,z-1)&&!g.solid(x,y,z))g.w(x,y,z)-=config.dt/config.density*(g.pressure(x,y,z)-g.pressure(x,y,z-1))/g.dz();enforceSolidFaces(g);out.divergenceL2After=divergenceL2(g);for(std::size_t z=0;z<g.nz();++z)for(std::size_t y=0;y<g.ny();++y)for(std::size_t x=0;x<g.nx();++x){const double uc=0.5*(g.u(x,y,z)+g.u(x+1,y,z)),vc=0.5*(g.v(x,y,z)+g.v(x,y+1,z)),wc=0.5*(g.w(x,y,z)+g.w(x,y,z+1));out.maxSpeed=std::max(out.maxSpeed,std::sqrt(uc*uc+vc*vc+wc*wc));}return out;}

} // namespace vulkax::solvers
