#include "vulkax/calibration/hyperelastic.hpp"

#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>

namespace vulkax::calibration {
namespace {
std::size_t parameterCount(HyperelasticFamily f){switch(f){case HyperelasticFamily::NeoHookean:return 1;case HyperelasticFamily::MooneyRivlin:return 2;case HyperelasticFamily::Yeoh3:return 3;}return 0;}
std::vector<double> basis(HyperelasticFamily f,double l){if(l<=0)throw std::invalid_argument("stretch must be positive");double a=l-1.0/(l*l);if(f==HyperelasticFamily::NeoHookean)return{a};if(f==HyperelasticFamily::MooneyRivlin)return{2*a,2*a/l};double q=l*l+2.0/l-3.0;return{2*a,4*a*q,6*a*q*q};}
std::vector<double> solve(std::vector<std::vector<double>>A,std::vector<double>b){std::size_t n=b.size();for(std::size_t k=0;k<n;++k){std::size_t p=k;for(std::size_t i=k+1;i<n;++i)if(std::abs(A[i][k])>std::abs(A[p][k]))p=i;if(std::abs(A[p][k])<1e-20)throw std::runtime_error("rank-deficient material calibration");std::swap(A[k],A[p]);std::swap(b[k],b[p]);for(std::size_t i=k+1;i<n;++i){double f=A[i][k]/A[k][k];for(std::size_t j=k;j<n;++j)A[i][j]-=f*A[k][j];b[i]-=f*b[k];}}std::vector<double>x(n);for(std::size_t ii=n;ii-->0;){double s=b[ii];for(std::size_t j=ii+1;j<n;++j)s-=A[ii][j]*x[j];x[ii]=s/A[ii][ii];}return x;}
}
double predictNominalStress(HyperelasticFamily f,const std::vector<double>&p,double l){auto b=basis(f,l);if(p.size()!=b.size())throw std::invalid_argument("hyperelastic parameter count mismatch");double y=0;for(std::size_t i=0;i<p.size();++i)y+=p[i]*b[i];return y;}
ModelFit fitModel(HyperelasticFamily family,const std::vector<StressDatum>&data){ModelFit fit;fit.family=family;const std::size_t k=parameterCount(family);if(data.size()<=k)return fit;std::vector<std::vector<double>> normal(k,std::vector<double>(k));std::vector<double> rhs(k);double totalWeight=0;try{for(const auto&d:data){if(d.weight<=0)return fit;auto b=basis(family,d.stretch);for(std::size_t i=0;i<k;++i){rhs[i]+=d.weight*b[i]*d.nominalStress;for(std::size_t j=0;j<k;++j)normal[i][j]+=d.weight*b[i]*b[j];}totalWeight+=d.weight;}fit.parameters=solve(std::move(normal),std::move(rhs));double rss=0;for(const auto&d:data){double e=predictNominalStress(family,fit.parameters,d.stretch)-d.nominalStress;rss+=d.weight*e*e;}fit.rmsError=std::sqrt(rss/totalWeight);double n=static_cast<double>(data.size());double safe=std::max(rss/n,1e-300);fit.aic=n*std::log(safe)+2.0*static_cast<double>(k);fit.bic=n*std::log(safe)+std::log(n)*static_cast<double>(k);fit.valid=std::all_of(fit.parameters.begin(),fit.parameters.end(),[](double v){return std::isfinite(v);});}catch(...){fit.valid=false;}return fit;}
ModelSelection selectModel(const std::vector<StressDatum>&data){ModelSelection out;for(auto f:{HyperelasticFamily::NeoHookean,HyperelasticFamily::MooneyRivlin,HyperelasticFamily::Yeoh3})out.fits.push_back(fitModel(f,data));double best=std::numeric_limits<double>::infinity();for(std::size_t i=0;i<out.fits.size();++i)if(out.fits[i].valid&&out.fits[i].bic<best){best=out.fits[i].bic;out.bestIndex=i;out.valid=true;}return out;}
ExperimentRecommendation recommendNextUniaxialStretch(const ModelSelection&s,const std::vector<double>&candidates){ExperimentRecommendation best;if(!s.valid||candidates.empty())return best;for(double l:candidates){if(l<=0)continue;std::vector<double>pred;for(const auto&fit:s.fits)if(fit.valid)pred.push_back(predictNominalStress(fit.family,fit.parameters,l));if(pred.size()<2)continue;double mean=0;for(double v:pred)mean+=v;mean/=pred.size();double var=0;for(double v:pred)var+=(v-mean)*(v-mean);var/=pred.size();double disagreement=std::sqrt(var)/std::max(std::abs(mean),1.0);if(!best.valid||disagreement>best.disagreement)best={l,disagreement,true};}return best;}
} // namespace vulkax::calibration
